version: '3.8'

x-service-default: &service-default
  logging:
    options:
      max-size: '100m'
      max-file: '2'

services:
  authserviceeventservices:
    <<: *service-default
    image: authserviceeventservices:latest
    hostname: simpledashboard.homeserver2.activator.com
    
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
    
    networks:
      traefik_ingress_network:
      
    deploy:
      mode: global
      placement:
        constraints:
           - 'node.role==manager'
      update_config:
        parallelism: 1
        delay: 180s

networks:
  traefik_ingress_network:
    external: true
    name: "logs-and-monitoring_ingress"
